name: slurpit
services:
  slurpit-warehouse:
    image: slurpit/warehouse:0.9.164
    container_name: slurpit-warehouse
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/services"]
      interval: 10s
      timeout: 10s
      retries: 360
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      WAREHOUSE_CALLBACK_SCANNER_URL: http://slurpit-portal/callback/scanner
      WAREHOUSE_CALLBACK_SCANNER_TOKEN:
      WAREHOUSE_CALLBACK_SCRAPER_URL: http://slurpit-portal/callback/scraper
      WAREHOUSE_CALLBACK_SCRAPER_TOKEN:
    volumes:
      - ./db/warehouse:/var/lib/mongodb
      - ./logs/warehouse/mongodb:/var/log/mongodb
      - ./logs/warehouse:/logs
    restart: always

  slurpit-scraper:
    image: slurpit/scraper:0.9.180
    container_name: slurpit-scraper
    depends_on:
      slurpit-warehouse:
        condition: service_healthy
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      SCRAPER_TIMEOUT: 20
      SCRAPER_POOLSIZE: 4
      SCRAPER_WAREHOUSE_URL: http://slurpit-warehouse
    volumes:
      - ./logs/scraper:/logs
    restart: always

  slurpit-scanner:
    image: slurpit/scanner:0.9.152
    container_name: slurpit-scanner
    depends_on:
      slurpit-warehouse:
        condition: service_healthy
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      SCANNER_POOLSIZE: 4
      SCANNER_TIMEOUT: 10
      SCANNER_WAREHOUSE_URL: http://slurpit-warehouse
    volumes:
      - ./logs/scanner:/logs
    restart: always

  slurpit-portal:
    image: slurpit/portal:1.1.37
    container_name: slurpit-portal
    networks:
      - autocon-workshop
    environment:
      TZ: Europe/Amsterdam
      PORTAL_BASE_URL: http://localhost
      PORTAL_WAREHOUSE_URL: http://slurpit-warehouse
      PORTAL_CREATE_DEFAULT_API_KEY: true
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - ./logs/mysql:/var/log/mysql/
      - ./logs/php:/var/log/php/
      - ./certs:/etc/nginx/certs/
      - ./db/portal:/var/lib/mysql
    restart: always

networks:
  autocon-workshop:
    external: true